version: "3.9"
services:
  db:
    platform: linux/x86_64
    container_name: db
    image: mysql:8.0.22
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d

  php:
    container_name: php-fpm
    build:
      context: ./php-fpm
      args:
        PHP_XDEBUG_MODE: ${PHP_XDEBUG_MODE}
        PHP_XDEBUG_CLIENT_PORT: ${PHP_XDEBUG_CLIENT_PORT}
        PHP_XDEBUG_CLIENT_HOST: ${PHP_XDEBUG_CLIENT_HOST}
        SYMFONY_CLI_VERSION: 4.23.2
    ports:
      - "${PHP_PORT}:9001"
    volumes:
      - ./symfony:/var/www/symfony:cached
      - ./logs/symfony:/var/www/symfony/var/log:cached
    depends_on:
      - db

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./symfony:/var/www/symfony:cached

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: bkzf-elastic
    ports:
      - 9200:9200
    volumes:
      - ./elastic/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  ofelia:
    container_name: ofelia
    image: mcuadros/ofelia:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ofelia/config.ini:/etc/ofelia/config.ini
